-- ========================================================
-- MPSC IT CLUB ORIENTATION DATABASE SCHEMA FOR SUPABASE
-- Mohammadpur Preparatory School & College IT Club
-- ========================================================

CREATE TABLE IF NOT EXISTS public.participants (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid TEXT UNIQUE NOT NULL,
    name TEXT NOT NULL,
    institute TEXT NOT NULL,
    ip_address TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.scores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    participant_uuid TEXT UNIQUE REFERENCES public.participants(uuid) ON DELETE CASCADE,
    participant_name TEXT NOT NULL,
    institute TEXT NOT NULL,
    game_type TEXT NOT NULL,
    score INT NOT NULL,
    total_questions INT NOT NULL,
    verification_code TEXT UNIQUE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.quiz_questions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question TEXT NOT NULL,
    option_a TEXT NOT NULL,
    option_b TEXT NOT NULL,
    option_c TEXT NOT NULL,
    option_d TEXT NOT NULL,
    correct_option CHAR(1) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.logo_questions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    prompt TEXT NOT NULL,
    logo_a_url TEXT NOT NULL,
    logo_b_url TEXT NOT NULL,
    correct_logo CHAR(1) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.settings (
    key TEXT PRIMARY KEY,
    value TEXT NOT NULL
);

INSERT INTO public.settings (key, value) VALUES
    ('quiz_timer', '45'),
    ('logo_timer', '30'),
    ('min_prize_score', '40')
ON CONFLICT (key) DO NOTHING;

ALTER TABLE public.participants ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.scores ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.quiz_questions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.logo_questions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.settings ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public select on participants" ON public.participants FOR SELECT USING (true);
CREATE POLICY "Allow public insert on participants" ON public.participants FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public delete on participants" ON public.participants FOR DELETE USING (true);

CREATE POLICY "Allow public select on scores" ON public.scores FOR SELECT USING (true);
CREATE POLICY "Allow public insert on scores" ON public.scores FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public delete on scores" ON public.scores FOR DELETE USING (true);

CREATE POLICY "Allow public select on quiz_questions" ON public.quiz_questions FOR SELECT USING (true);
CREATE POLICY "Allow public insert on quiz_questions" ON public.quiz_questions FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public delete on quiz_questions" ON public.quiz_questions FOR DELETE USING (true);

CREATE POLICY "Allow public select on logo_questions" ON public.logo_questions FOR SELECT USING (true);
CREATE POLICY "Allow public insert on logo_questions" ON public.logo_questions FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public delete on logo_questions" ON public.logo_questions FOR DELETE USING (true);

CREATE POLICY "Allow public select on settings" ON public.settings FOR SELECT USING (true);
CREATE POLICY "Allow public insert on settings" ON public.settings FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update on settings" ON public.settings FOR UPDATE USING (true);
